---
services:
  app:
    image: "node:20.11.1"
    container_name: it-navigator-app
    working_dir: /app
    volumes:
      - ./:/app
    network_mode: "host"
    expose:
      - "5173"
    command: ["sh", "-c", "yarn install && yarn run dev"]
